# Generated by Django 3.2.3 on 2022-04-24 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enterprise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
            ],
            options={
                'verbose_name': '资格证书',
                'db_table': 'credentials',
            },
        ),
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('title', models.CharField(max_length=255, verbose_name='工作类型')),
                ('sub', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='self', to='Job_seekers.jobtype', verbose_name='子集工作类型')),
            ],
            options={
                'verbose_name': '工作类型',
                'db_table': 'job_type',
            },
        ),
        migrations.CreateModel(
            name='ProjectExperience',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('createTime', models.DateTimeField(verbose_name='创建时间')),
                ('updateTime', models.DateTimeField(verbose_name='修改时间')),
                ('delete', models.IntegerField(choices=[(0, '用户删除'), (1, '正常状态')], default=1, verbose_name='删除')),
                ('startTime', models.CharField(max_length=255, null=True, verbose_name='开始时间')),
                ('endTime', models.CharField(max_length=255, null=True, verbose_name='结束时间')),
                ('project_name', models.CharField(max_length=255, verbose_name='项目名称')),
                ('project_description', models.CharField(max_length=1000, verbose_name='工作描述')),
            ],
            options={
                'verbose_name': '项目经历',
                'db_table': 'project_experience',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('createTime', models.DateTimeField(verbose_name='创建时间')),
                ('updateTime', models.DateTimeField(verbose_name='修改时间')),
                ('delete', models.IntegerField(choices=[(0, '用户删除'), (1, '正常状态')], default=1, verbose_name='删除')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('avatarUrl', models.CharField(max_length=255, verbose_name='头像')),
                ('notes', models.CharField(max_length=1000, null=True, verbose_name='备注')),
                ('address', models.CharField(max_length=255, null=True, verbose_name='地址')),
                ('phone', models.CharField(max_length=255, null=True, verbose_name='联系电话')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='邮箱')),
                ('passWord', models.CharField(max_length=20, verbose_name='密码')),
                ('birthday', models.DateTimeField(verbose_name='出生日期')),
                ('height', models.IntegerField(null=True, verbose_name='身高')),
                ('weight', models.IntegerField(null=True, verbose_name='体重')),
                ('qualifications', models.CharField(max_length=55, null=True, verbose_name='学历')),
                ('gender', models.IntegerField(choices=[(0, '男'), (1, '女'), (2, '隐身状态')], verbose_name='性别')),
            ],
            options={
                'verbose_name': '求职用户',
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('createTime', models.DateTimeField(verbose_name='创建时间')),
                ('updateTime', models.DateTimeField(verbose_name='修改时间')),
                ('delete', models.IntegerField(choices=[(0, '用户删除'), (1, '正常状态')], default=1, verbose_name='删除')),
                ('startTime', models.CharField(max_length=255, null=True, verbose_name='开始时间')),
                ('endTime', models.CharField(max_length=255, null=True, verbose_name='结束时间')),
                ('enterprise_name', models.CharField(max_length=255, verbose_name='企业名称')),
                ('job_description', models.CharField(max_length=1000, verbose_name='工作描述')),
                ('label', models.ManyToManyField(db_table='Work_experience_label', to='enterprise.Label', verbose_name='职位标签')),
            ],
            options={
                'verbose_name': '工作经历',
                'db_table': 'work_experience',
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('createTime', models.DateTimeField(verbose_name='创建时间')),
                ('updateTime', models.DateTimeField(verbose_name='修改时间')),
                ('delete', models.IntegerField(choices=[(0, '用户删除'), (1, '正常状态')], default=1, verbose_name='删除')),
                ('self_assessment', models.CharField(max_length=2000, verbose_name='自我评价')),
                ('job_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Job_seekers.jobtype', verbose_name='工作类型')),
                ('label', models.ManyToManyField(to='enterprise.Label', verbose_name='职位标签')),
            ],
            options={
                'verbose_name': '工作简历',
                'db_table': 'resume',
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('createTime', models.DateTimeField(verbose_name='创建时间')),
                ('updateTime', models.DateTimeField(verbose_name='修改时间')),
                ('delete', models.IntegerField(choices=[(0, '用户删除'), (1, '正常状态')], default=1, verbose_name='删除')),
                ('interviewTime', models.DateTimeField(null=True, verbose_name='面试时间')),
                ('interview_address', models.CharField(max_length=255, null=True, verbose_name='面试地址')),
                ('state', models.IntegerField(default=0, verbose_name='面试状态值')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_position', to='enterprise.position', verbose_name='职位信息')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_user', to='Job_seekers.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '邀请面试',
                'db_table': 'interview',
            },
        ),
        migrations.CreateModel(
            name='Delivery_record',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('createTime', models.DateTimeField(verbose_name='创建时间')),
                ('updateTime', models.DateTimeField(verbose_name='修改时间')),
                ('delete', models.IntegerField(choices=[(0, '用户删除'), (1, '正常状态')], default=1, verbose_name='删除')),
                ('state', models.IntegerField(choices=[(0, '待阅读'), (1, '已阅读')], default=0, verbose_name='阅读状态')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_position', to='enterprise.position', verbose_name='职位信息')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_position', to='Job_seekers.resume', verbose_name='简历')),
            ],
            options={
                'verbose_name': '简历投递记录',
                'db_table': 'delivery_record',
            },
        ),
    ]
